backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: slider
    label: Slider
    folder: "content/slider"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Judul, name: title, widget: string }
      - { label: Gambar, name: image, widget: image }

  - name: galeri
    label: Galeri
    folder: "content/galeri"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Judul, name: title, widget: string }
      - { label: Gambar, name: image, widget: image }

  - name: agenda
    label: Agenda
    folder: "content/agenda"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Judul, name: title, widget: string }
      - { label: Tanggal, name: tanggal, widget: string }
      - { label: Deskripsi, name: deskripsi, widget: text }
      - { label: Gambar, name: image, widget: image }

  - name: pengumuman
    label: Pengumuman
    folder: "content/pengumuman"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Judul, name: title, widget: string }
      - { label: Isi, name: body, widget: markdown }

  - name: prestasi
    label: Prestasi
    folder: "content/prestasi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Judul Prestasi, name: title, widget: string }
      - { label: Keterangan, name: keterangan, widget: string }
